config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "snippets/show"

  get "/support/cookie", :controller => "support", :action => "cookie"

  get "/samples", :controller => "samples", :action => "index"
  get "/samples/:page" => "samples#show"
  post "/samples/:page" => "samples#show"
 
  namespace :admin do
    resources :examples, :products, :versions, :categories, :snippets, :attachments, :users
    get "/help/(:type)", :controller => "help", :action => "index", :as => "help"
    get "feedback/list", :controller => "feedback", :action => "list"
    get "feedback/list/:id", :controller => "feedback", :action => "view", :as => "example_feedback"
    delete "feedback/:id", :controller => "feedback", :action => "destroy", :as => "feedback_delete"
  end
  
  get "/js/:action(.:format)", :controller => "js"
  
  post "/feedback/(:id)", :controller => "feedbacks", :action => "create", :as => "feedbacks"

  get "/search/(:q)", :controller => "examples", :action => "search", :as => "examples_search"

  get "/examples(.:format)", :controller => "examples", :action => "index", :as => "examples_index"
  get "/legacy(.:format)", :controller => "examples", :action => "legacy", :as => "examples_legacy_index"

  get "/snippets/:id", controller: 'snippets', action: 'show'

  get "/:id(.:language)", :constraints => {:id => /[0-9]+/}, :controller => 'examples', :action => 'show_id', :as => 'example_id'
  get "/Toolkit_Professional(/:version(/:title(.:language)))", to: redirect { |path_params, req| "/Toolkit/#{path_params[:version]}/#{path_params[:title]}.#{path_params[:language]}" }
  get "/:product/:version/download.:language", :controller => "examples", :action => "download_all_examples", :as => "examples_download"
  get "/:product(/:version(/:title(.:language)))", :controller => "examples", :action => "show", :as => "examples"
  get "/:product/:version/:title.:language/documentation", :controller => "examples", :action => "documentation", :as => "example_documentation"
  get "/:product/:version/:title.:language/download", :controller => "examples", :action => "download", :as => "example_download"
  get "/:product/:version/:title.:language/download_all", :controller => "examples", :action => "download_all", :as => "example_download_all"
  get "/:product/:version/:title.:language/download_package", :controller => "examples", :action => "download_package", :as => "example_download_package"

  post "/contact_mailer", :controller => "contact", :action => "create"

  root :to => "examples#index"

end

app/controllers/admin/examples_controller.rb
class Admin::ExamplesController < Admin::AdminController
  load_and_authorize_resource
  before_filter :set_page_id
  before_filter :set_products_versions

  def set_page_id
   @page_id = "admin"
   @title = "Admin Examples"
  end
  
  def get_potential_clones
    # Gather array of products and examples usable with options_for_select
    @potential_clones = Hash.new
    @potential_clones[:products] = Array.new
    @potential_clones[:examples] = Hash.new
    
    # Add empty product for selection of no clone
    @potential_clones[:products] << ["none", "none"]
    @potential_clones[:examples]["none"] = ["none", "none"]
    
    Product.order('name').each do |p|
      # Get each product and assign it to :products
      @potential_clones[:products] << [p.name,p.id]
      @potential_clones[:examples][p.id] = Array.new
      
      # For each product, get the examples linked to it
      examples = p.examples.order('title')
      examples.where(["examples.id != ?",@example.id]) if @example.id
      examples.each do |e|
        @potential_clones[:examples][p.id] << [e.title,e.id]
      end
    end
    
    @potential_clones[:examples].each do |id,data|
      # Remove any products that have no examples
      if data.empty?
        product = Product.find(id)
        @potential_clones[:products].delete([product.name,product.id])
        @potential_clones[:examples].delete(id)
      end
    end
  end
  
  def index
    @examples = Example.page(params[:page])
  end
  
  def new
    @example = Example.new
    @example.code = "with_version do |n|\n  \nend"
    @products = Product.all
    @submit_path = admin_examples_path
    @example.category_id = Category.where(name: 'Unknown').first.id
    get_potential_clones
  end
  
  def update
    params[:example][:attachment_ids] ||= []
    @example = Example.find(params[:id])
    @products = Product.all
    @submit_path = admin_example_path(@example)
    
    get_potential_clones
        
    if @example.update_attributes(example_params)
      @example.reload
      
      # if we have a "ref" to redirect to, then use it
      if params[:ref]
        url = params[:ref]
      else
        ref = {
          :product => @example.products.first.name,
          :version => @example.products.first.latest_version.name,
          :title => @example.title
        }
        url = examples_path ref
      end
      
      redirect_to url, :notice => "Example #{t(:update_success)}"
    else
      render :action => "new"
    end
  end
  
  def edit
    @example = Example.find(params[:id])
    @products = Product.all
    @submit_path = admin_example_path(@example)
    @feedback = Feedback.where("content LIKE 'example-#{@example.id}%'")
    
    @title = "#{@example.id}: #{@example.title} - Edit Example"
    
    get_potential_clones
  end
  
  def destroy
    @example = Example.find(params[:id])
    if @example.destroy
      redirect_to admin_examples_path, :notice => "Example was deleted."
    else
      render :action => "index", :notice => "There was an error deleting the example."
    end
  end
  
  def create
    params[:example][:attachment_ids] ||= []
    @example = Example.new(example_params)
    @products = Product.all
    @attachments = Attachment.all
    @submit_path = admin_examples_path
    
    if @example.save
      @example.reload
      redirect_to examples_path(:product => @example.products.first.name, :version => @example.products.first.latest_version_from_all.name, :title => @example.title), :notice => "Example was successfully created."
      # p @example.products
    else
      get_potential_clones
      render :action => "new"
    end
  end

  private
  def example_params
    params.require(:example).permit!
  end

end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_filter :set_page_id
  before_filter :validate_params, :only => [:download, :show, :documentation, :download_all, :download_all_examples]
  before_filter :get_example_details, :only => [:download, :show, :documentation, :download_all]

  skip_before_action :verify_authenticity_token, only: :search
  
  respond_to :zip, :only => :download
  
  def non_admin_example_access?
    if @example
      # Send the user to the examples index path if they are trying to access an example that is not active
      unless can?(:read, @example)
        # redirect_to root_path, :notice => "I'm sorry, that example is not available."
        raise CanCan::AccessDenied
      end
    end
  end
  
  def set_page_id
   @page_id = "examples"
  end
  
  def show_id
    begin
      redirect_to example_default_path(params[:id].to_i, params[:language])
    rescue
      redirect_to examples_index_path, :notice => "I'm sorry that example was not found."
    end
  end
  
  def get_documentation_details
    @documentation = parse_generic_documentation(@example.documentation, @language) if @example && @example.documentation
    if @documentation && (@example.list_type == "method" || @example.list_type == "property")
      @syntax = parse_generic_documentation_syntax(@documentation, @language)
    end
  end
  
  def index
    @active = Product.active
    @future = Product.future
  end
  
  def legacy
    @active = Product.active
    @future = Product.future
    @legacy = Product.legacy
  end

  def get_all_snippets(snippet_list, snippet_exclude_list)
    # puts "Snippet list: #{snippet_list.inspect}"
    # puts "Snippet exclude list: #{snippet_exclude_list.inspect}"
    
    snippets = Hash.new
    snippet_list.each do |sc|
      sc = Category.find(sc)
      Category.where(:id => sc).each do |c|
        snippets[sc] = Array.new unless snippets.include?(sc)
        snippets[sc] = Snippet.find_all_by_product_id_and_version_sort_order_and_category_id(@product.id, @version.sort_order, sc).collect {|s| [s.name, s.id] }

      end
    end
    
    # remove snippets that are excluded from snippet hash
    unless snippet_exclude_list.empty?
      snippets.each do |c,s|
        s.delete_if {|s| snippet_exclude_list.include?(s[1])}
      end
      snippets.delete_if {|c,s| s.length <= 1}
    end
    
    return snippets
  end
  
  def show
    non_admin_example_access?
    
    if @example
      @example_related = Hash.new
      @example_related[:methods] = @example.find_related_tags.is_method
      @example_related[:properties] = @example.find_related_tags.is_property
      @example_related[:advanced] = @example.find_related_tags.is_advanced
    end
    
    @products = Product.order("name ASC")
    
    # Setup feedback form
    @feedback = Feedback.new
        
    if @example
      if @language == "json"
        # parsed_code = parse_generic_code(@example.code, "cs")
        # json_code = {:status => "success", :body => parsed_code[:code]}
        json_code = {:status => "success"}
        parsed_code = parse_generic_code(@example.code, "cs")
        json_code[:cs] = parsed_code[:code]
        parsed_code = parse_generic_code(@example.code, "vb")
        json_code[:vb] = parsed_code[:code]
        parsed_code = parse_generic_code(@example.code, "vbs")
        json_code[:vbs] = parsed_code[:code]
        parsed_code = parse_generic_code(@example.code, "asp")
        json_code[:asp] = parsed_code[:code]
        parsed_code = parse_generic_code(@example.code, "php")
        json_code[:php] = parsed_code[:code]
        parsed_code = parse_generic_code(@example.code, "cfm")
        json_code[:cfm] = parsed_code[:code]
        parsed_code = parse_generic_code(@example.code, "rb")
        json_code[:rb] = parsed_code[:code]
        parsed_code = parse_generic_code(@example.code, "ps1")
        json_code[:ps1] = parsed_code[:code]
        parsed_code = parse_generic_code(@example.code, "shell")
        json_code[:shell] = parsed_code[:code]
        parsed_code = parse_generic_code(@example.code, "html")
        json_code[:html] = parsed_code[:code]

        render :json => json_code
      else
        if params.has_key?(:json)
          @ValidExample = false
          case @language
          when "cs"
            if @example.cs
              @ValidExample = true
            end    
          when "vb"
            if @example.vb
              @ValidExample = true
            end
          when "vbs"
            if @example.vbs
              @ValidExample = true
            end
          when "asp"
            if @example.asp
              @ValidExample = true
            end
          when "php"
            if @example.php
              @ValidExample = true
            end
          when "cfm"
            if @example.cfm
              @ValidExample = true
            end
          when "rb"
            if @example.rb
              @ValidExample = true
            end
          when "ps1"
            if @example.ps1
              @ValidExample = true
            end
          when "shell"
            if @example.shell
              @ValidExample = true
            end
          when "html"
            if @example.html
              @ValidExample = true
            end
          end

          if @ValidExample
            parsed_code = parse_generic_code(@example.code, @language)
            json_code = {:status => "success", :body => parsed_code[:code]}
          else
            json_code = {:status => "success", :body => "#{@language} is not available with this example."}
          end
          render :json => json_code
        else
          parsed_code = parse_generic_code(@example.code, @language)

          @code = parsed_code[:code]
          @error = parsed_code[:error]
          @code_file = parsed_code[:code_file]
          @code_aspx = parsed_code[:code_aspx]
          @portal_aspx = parsed_code[:portal_aspx] if @product.name == "Portal"

          if parsed_code[:snippets] && !parsed_code[:snippets].empty?
            @snippet_categories = get_all_snippets(parsed_code[:snippets], parsed_code[:snippets_to_exclude])
            @snippet_categories_selected = parsed_code[:snippets_to_use].empty? ? parsed_code[:snippets_in_use] : parsed_code[:snippets_to_use]
            @snippets_defaults = parsed_code[:snippets_defaults]
          end

          @title_full = "#{@example.title}: ActivePDF #{@product.name} - #{Example.full_language_name_by_shortname[@language]} Code" # set page title
          @meta_description = "#{@example.title} example written in #{Example.full_language_name_by_shortname[@language]} for ActivePDF #{@product.name} #{@version.name}."
          @meta_keywords = "#{@example.title}, ActivePDF #{@product.name}, ActivePDF #{@product.name} example, #{@product.name}, #{@product.name} #{@version.name}"
        end
      end
    else
      respond_to do |format|
        format.html
        format.json {
          output = []
          examples = []
          examples << @examples_advanced.is_original
          examples << @examples_functions.is_original
          examples.flatten.each do |e|
            @example = e # parse_generic_code requires @example be set
            
            # get a list of snippet categories in use for this example
            parsed_code = parse_generic_code(e.code, 'cs')

            if parsed_code[:snippets] && !parsed_code[:snippets].empty?
              # we found snippets, let's get all the categories, and options
              all_snippets = get_all_snippets(parsed_code[:snippets], parsed_code[:snippets_to_exclude])
              snippet_categories = Hash.new{|h,k| h[k]= Array.new}
              all_snippets.each do |cat,snips|
                snippet_categories["snippets[#{cat.id}]"] = snips.map{|x|x[1]}
              end
              
              # voodoo magic to get all combinations of snippets
              ary = snippet_categories.map {|k,v| [k].product v}
              ary.shift.product(*ary).map {|a| Hash[a]}.each do |combination|
                # get the url for an example, with the combination of snippets
                options = {:product => @product.name, :version => @version.name, :title => e.title, :language => nil}.merge(combination)
                output << examples_url(options)
              end
              

            else
              # no snippets
              output << examples_url(:product => @product.name, :version => @version.name, :title => e.title, :language => nil)
            end
          end
          render :json => output
        }
      end
    end
  end
  
  def search
    tags = params[:t].split(',') if params[:t]
    
    if params[:q]
      @by_title = Example.where("title LIKE ?", "%#{params[:q]}%").is_active
      @by_title = @examples.tagged_with(tags) if tags
      
      @by_tags = Example.tagged_with(params[:q].split(' '))
      
      @examples = @by_title.concat(@by_tags)
      
      Category.where("name LIKE ?", "%#{params[:q]}%").each do |c|
        c.examples.each do |e|
          @examples << e
        end
      end
      
      @examples.uniq!
      @term = params[:q]
      @language = params[:language].empty? ? "cs" : params[:language]
    else
      @examples = []
    end
  end
  
  def download
    non_admin_example_access?

    begin
      parsed_code = parse_generic_code(@example.code, params[:language])
      code = parsed_code[:code]

      attachments = Array.new
      # For each snippet that is used, pull in their attachments
      parsed_code[:snippets_in_use].each do |sid|
        attachments << Snippet.find(sid).attachments
      end
    
      # Pull in the parent clone's attachments
      attachments << @example.cloned_attachments unless @example.cloned_attachments.empty?
    
      # For any files that were used inside the code, get those attachments too.
      parsed_code[:files].each do |file|

app/helpers/examples_helper.rb
module ExamplesHelper
  def language_options_for_select(selected)
    options_for_select(languages, selected)
  end
  
  def example_languages_paths(options = {})
    example = Example.find(options[:example_id])
    options[:version] ||= example.versions.order("sort_order ASC").last.name
    urls = Hash.new
    Example.all_languages.each do |name,value|
      urls[value] = examples_path(:product => example.product.name, :version => options[:version], :title => example.title, :language => value)
    end
    return urls
  end
  
  def example_list_item_class(type)
    case type
    when "method"
      "example_list_item_method"
    when "property"
      "example_list_item_property"
    when "advanced"
      "example_list_item_advanced"
    else
      ""
    end
  end
end

app/views/admin/examples/_example_form.html.slim
javascript:
  $.ctrl('S', function(){
    $('form.edit_example').submit();
  });

= raw version_start_end_js("example")

= form_for @example, :url => @submit_path do |f|
  input type="hidden" name="ref" value="#{request.referer}"
  .row.form_example
    .col-md-3
      h3 Details

      .form-group
        => f.label :title
        - unless @example.new_record?
          = link_to "view", example_id_path(@example.id), :target => "_blank"
        = f.text_field :title, :class => "form-control"

      / .form-group
      /   => f.label :display_title
      /   = f.text_field :display_title, :class => "form-control"

      .form-group
        => f.label :description
        = f.text_area :description, :class => "form-control", :style => "height: 94px;"

      .form-group
        = f.label :Category
        br
        = collection_select(:example, :category_id, Category.order("name").all, :id, :name, {}, {:class => "form-control input-sm"})

      .form-group
        = f.label :status
        br
        = select_tag "example[status]", options_for_select(Example.statuses, @example.status), :class => "form-control input-sm"
      
      javascript:
        function updateStatus() {
          if ( $('#clone_id').val() === "none" || $('#clone_id').val() == "") {
            // enable status selection
            $('#example_status').removeAttr('disabled');
          } else {
            // disable status selection
            $('#example_status').attr('disabled', 'disabled');
          }
        }
        
        $(document).ready(function() {          
          updateStatus();
        });
    
      .form-group
        = f.label :type
        br
        => f.radio_button(:example_type, "basic")
        => f.label :example_type_basic, "Function"
        => f.radio_button(:example_type, "advanced")
        = f.label :example_type_advanced, "Advanced"

      .form-group
        => f.check_box :is_method
        = f.label :is_method?, "Method"

      hr

      .form-group
        = f.label :products
        br
        = render :partial => 'admin/shared/multi_products_select', :locals => {:model => "example", :selected => @example.example_versions, :potential => @example.potential_products}
      
      hr

      .form-group
        = f.label :languages
        br
        => f.check_box :cs
        = f.label :cs, "C#"
        br
        => f.check_box :vb
        = f.label :vb, "VB"
        br
        => f.check_box :vbs
        = f.label :vbs, "VBS"
        br
        => f.check_box :asp
        = f.label :asp, "ASP"
        br
        => f.check_box :ps1
        = f.label :ps1, "PowerShell"
        br
        => f.check_box :php
        = f.label :php, "PHP"
        br
        => f.check_box :cfm
        = f.label :cfm, "CF"
        br
        => f.check_box :rb
        = f.label :rb, "Ruby"
        br
        => f.check_box :shell
        = f.label :shell, "Shell"
        br
        => f.check_box :html
        = f.label :html, "HTML"

      .form-group#attachments_div
        hr
        = f.label :attachments
        .attachments_list
          - Attachment.all.each do |a|
            => check_box_tag "example[attachment_ids][]", a.id, @example.attachments.include?(a) 
            = label_tag "example[attachment_ids][#{a.id}]", a.file_file_name
            br

      hr

      .form-group
        = f.label :video
        = f.text_field :video, :class => "form-control"

      .form-group
        javascript:
          $(function() {
            // This line needs to be updated to work with SLIM
            var availableTags = raw Example.tag_counts.collect{|t| t.name }.uniq.to_json;
            function split( val ) {
              return val.split( /,\s*/ );
            }
            function extractLast( term ) {
              return split( term ).pop();
            }

            $( "#example_tags" )
              // don't navigate away from the field on tab when selecting an item
              .bind( "keydown", function( event ) {
                if ( event.keyCode === $.ui.keyCode.TAB &&
                    $( this ).data( "autocomplete" ).menu.active ) {
                  event.preventDefault();
                }
              })
              .autocomplete({
                minLength: 0,
                source: function( request, response ) {
                  // delegate back to autocomplete, but extract the last term
                  response( $.ui.autocomplete.filter(
                    availableTags, extractLast( request.term ) ) );
                },
                focus: function() {
                  // prevent value inserted on focus
                  return false;
                },
                select: function( event, ui ) {
                  var terms = split( this.value );
                  // remove the current input
                  terms.pop();
                  // add the selected item
                  terms.push( ui.item.value );
                  // add placeholder to get the comma-and-space at the end
                  terms.push( "" );
                  this.value = terms.join( ", " );
                  return false;
                }
              });
          });

        = f.label :tags
        = f.text_field :tag_list, :class => "form-control", :id => "example_tags"

      = hidden_field_tag "example[edited_by]", current_user.email
      - if @example.new_record?
        = hidden_field_tag "example[created_by]", current_user.email
      - else
        .form-group
          = f.label :created_by
          p = @example.created_by        

        .form-group
          = f.label :edited_by
          p = @example.edited_by


    .col-md-9
      h3.pull-left Code
      span.pull-right
        => f.submit :class => "btn btn-primary btn-xs"
        - unless @example.new_record?
          => link_to "Delete", admin_example_path(@example), :class => "btn btn-danger btn-xs", :method => :delete, :confirm => "Are you sure?"
        = link_to "help", admin_help_path(:type => "examples"), :target => "_blank", :class => "btn btn-info btn-xs"
      .clearfix

      .form-group#generic_code_container
        => f.label :generic_code
        .generic_code_box
          = f.text_area :code, :class => "form-control edit_box_code"
          = render :partial => 'admin/shared/codemirror', :locals => {:container_id => 'example_code'}
          / br
          / = f.text_area :code, :class => "form-control edit_box_code", :id => "editor"
          / = render :partial => 'examples/ace_editor', :locals => {:id => 'editor', :language => 'ruby'}
    
      h4 Clones
      .row
        .col-md-6
          .form-group
            = f.label :clone_example, "Choose Example to Clone"
            = select_tag "product_clone_id", options_for_select(@potential_clones[:products]), :class => "form-control input-sm"
            - @potential_clones[:products].each do |prod|
              = select_tag "clone_product_#{prod[1]}", options_for_select(@potential_clones[:examples][prod[1]]), :class => "clone_example_select form-control input-sm"

            input id="clone_id" type="hidden" name="example[clone_id]" value="#{@example.clone_id}"
            span id="cloned_edit_link_container" style="display: none;"
              = link_to "edit clone", "#", :id => "cloned_edit_link", :class => "btn btn-primary btn-xs"

          javascript:
            setCloneValue = function(id) {
              if (id == "none") {
                $('#clone_id').val('');
              } else {
                $('#clone_id').val(id);
                url = '#{edit_admin_example_path(:id => 0)}';
                url = url.replace('0',id);
                $('#cloned_edit_link').attr('href',url);
              }
            }
            
            getCloneValue = function() {
              ret = $('#clone_id').val();
              if (typeof(ret) === "undefined") {
                return "";
              } else {
                return ret;
              }
            }
            
            $('#product_clone_id').change(function(){
              product = $(this).val();
              $('.clone_example_select').hide();
              $('#clone_product_' + product).show();
              setCloneValue($('#clone_product_' + product).val());
              if ($(this).val() == "none") {
                $('#generic_code_container').show(1000);
                $('#attachments_div').show(1000);
                $('#cloned_edit_link_container').hide(1000);
                $('.clone_example_select').hide(1000);
              } else {
                $('#generic_code_container').hide(1000);
                $('#cloned_edit_link_container').show(1000);
                $('#attachments_div').hide(1000);
              }
              updateStatus();
            });
            
            $('.clone_example_select').change(function(){
              setCloneValue($(this).val());
            });
            
            $(document).ready(function() {
              if (getCloneValue() == "") {
                $('.clone_example_select').hide();
              } else {
                $('.clone_example_select').hide();
                $('#generic_code_container').hide();
                $('#cloned_edit_link_container').show();
                setCloneValue($('.clone_example_select option[value='+getCloneValue()+']').val());
                id = $('.clone_example_select option[value='+getCloneValue()+']').parent().attr('id').match(/[0-9]+/);
                $('#product_clone_id').val(id);
                $('#clone_product_' + id).val(getCloneValue()).show();
                $('#attachments_div').hide();
              }
            });

        .col-md-6
          - unless @example.clones.length == 0
            .form-group
              = f.label :clones, "Clones"
              ul.list-unstyled
                - @example.clones.each do |c|
                  li = link_to c.title, edit_admin_example_path(c.id)

      - unless @example.new_record? || @feedback.nil? || @feedback.empty?
        .form-group
          = f.label :feedback_summary
          table.table
            thead
              tr
                td Total
                td Average rating
                td Details
            tbody
              tr
                td = @feedback.length
                td = Feedback.average_rating_for_example_id(@example.id)
                td = link_to "view", admin_example_feedback_path(:id => @example.id)

app/views/admin/examples/edit.html.erb
<% if @example.errors.any? %>
  <ul>
    <% @example.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render "example_form" %>

app/views/admin/examples/index.html.erb
<h2>Examples</h2>
<%= paginate @examples %>
<div class="table_list">
	<table class="table">
		<thead class="table_list_head">
		  <tr>
		    <th>ID</th>
		    <th>Title</th>
		    <th>Product</th>
				<th>Type</th>
				<th>Function</th>
				<th>Category</th>
		    <th></th>
		  </tr>
		</thead>
		<tbody class="table_list_body">
		  <% @examples.each do |e| %>
		  <tr>
		    <td><%= e.id %></td>
				    <td><%= link_to e.title, edit_admin_example_path(e) %></td>
				<td><%= e.products.first.name %></td>
		    <td><%= e.example_type %></td>
				<td>
					<% if e.is_method == true %>
						Method
					<% else %>
						Property
					<% end %>
				</td>
				<td><%= e.category.name if e.category %></td>
				<td><%= link_to "x", admin_example_path(e), :method => :delete, :confirm => "Are you sure?" %></td>
		  </tr>
		  <% end %>
		</tbody>
		<tfoot class="table_list_foot">
			<tr>
				<td colspan="100%">
						<%= link_to "New Example", new_admin_example_path %>
				</td>
			</tr>
		</tfoot>
	</table>
</div>

app/views/admin/examples/new.html.erb
<% if @example.errors.any? %>
  <ul>
    <% @example.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render "example_form" %>