config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "snippets/show"

  get "/support/cookie", :controller => "support", :action => "cookie"

  get "/samples", :controller => "samples", :action => "index"
  get "/samples/:page" => "samples#show"
  post "/samples/:page" => "samples#show"
 
  namespace :admin do
    resources :examples, :products, :versions, :categories, :snippets, :attachments, :users
    get "/help/(:type)", :controller => "help", :action => "index", :as => "help"
    get "feedback/list", :controller => "feedback", :action => "list"
    get "feedback/list/:id", :controller => "feedback", :action => "view", :as => "example_feedback"
    delete "feedback/:id", :controller => "feedback", :action => "destroy", :as => "feedback_delete"
  end
  
  get "/js/:action(.:format)", :controller => "js"
  
  post "/feedback/(:id)", :controller => "feedbacks", :action => "create", :as => "feedbacks"

  get "/search/(:q)", :controller => "examples", :action => "search", :as => "examples_search"

  get "/examples(.:format)", :controller => "examples", :action => "index", :as => "examples_index"
  get "/legacy(.:format)", :controller => "examples", :action => "legacy", :as => "examples_legacy_index"

  get "/snippets/:id", controller: 'snippets', action: 'show'

  get "/:id(.:language)", :constraints => {:id => /[0-9]+/}, :controller => 'examples', :action => 'show_id', :as => 'example_id'
  get "/Toolkit_Professional(/:version(/:title(.:language)))", to: redirect { |path_params, req| "/Toolkit/#{path_params[:version]}/#{path_params[:title]}.#{path_params[:language]}" }
  get "/:product/:version/download.:language", :controller => "examples", :action => "download_all_examples", :as => "examples_download"
  get "/:product(/:version(/:title(.:language)))", :controller => "examples", :action => "show", :as => "examples"
  get "/:product/:version/:title.:language/documentation", :controller => "examples", :action => "documentation", :as => "example_documentation"
  get "/:product/:version/:title.:language/download", :controller => "examples", :action => "download", :as => "example_download"
  get "/:product/:version/:title.:language/download_all", :controller => "examples", :action => "download_all", :as => "example_download_all"
  get "/:product/:version/:title.:language/download_package", :controller => "examples", :action => "download_package", :as => "example_download_package"

  post "/contact_mailer", :controller => "contact", :action => "create"

  root :to => "examples#index"

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  belongs_to :category
  has_and_belongs_to_many :attachments
  has_many :snippet_versions, :dependent => :destroy
  has_many :products, :through => :snippet_versions
  
  validates_presence_of :name, :code, :category
  
  before_save :flush_cache
  
  include MultipleProducts
  
  def self.find_all_by_product_id_and_version_sort_order_and_category_id(product_id, sort_order, category_id)
    snippets = self.where(["products.id = ?", product_id])
      .joins(:snippet_versions)
      .joins(:products)
      .joins("LEFT JOIN versions vs ON snippet_versions.version_id_start = vs.id")
      .joins("LEFT JOIN versions ve ON snippet_versions.version_id_end = ve.id")
      .where(["? BETWEEN vs.sort_order AND ifnull(ve.sort_order,999999999)", sort_order])
      .where(["snippet_versions.product_id = ?",product_id])
      .where(:category_id => category_id)
      .order("snippets.name ASC")
  end

  def self.find_all_by_product_id_and_version_sort_order(product_id, sort_order)
    snippets = self.where(["products.id = ?", product_id])
      .joins(:snippet_versions)
      .joins(:products)
      .joins("LEFT JOIN versions vs ON snippet_versions.version_id_start = vs.id")
      .joins("LEFT JOIN versions ve ON snippet_versions.version_id_end = ve.id")
      .where(["? BETWEEN vs.sort_order AND ifnull(ve.sort_order,999999999)", sort_order])
      .where(["snippet_versions.product_id = ?",product_id])
      .order("snippets.name ASC")
  end
  
  protected
  def flush_cache
    # Rails.cache.clear
  end
end

app/controllers/admin/snippets_controller.rb
class Admin::SnippetsController < Admin::AdminController
  load_and_authorize_resource
  before_filter :set_page_id
  
  def set_page_id
   @page_id = "admin"
   @title = "Admin Snippets"
  end
  
  def index
    @categories = Category.with_snippets.order('name')
  end
  
  def new
    @snippet = Snippet.new
    @snippet.category_id = Category.where(name: 'Unknown').first.id
    @submit_path = admin_snippets_path
    set_products_versions
  end
  
  def create
    @snippet = Snippet.new(snippet_params)
    @submit_path = admin_snippets_path
    set_products_versions
    if @snippet.save
      redirect_to admin_snippets_path, :notice => "Snippet was successfully updated."
    else
      render :action => "new"
    end
  end
  
  def edit
    @snippet = Snippet.find(params[:id])
    @submit_path = admin_snippet_path(@snippet)
    set_products_versions
    @title = "#{@snippet.id}: #{@snippet.name} - Edit Snippet"
  end
  
  def update
    params[:snippet][:attachment_ids] ||= []
    @snippet = Snippet.find(params[:id])
    @submit_path = admin_snippet_path(@snippet)
    set_products_versions
    if @snippet.update_attributes(snippet_params)
      redirect_to admin_snippets_path, :notice => "Snippet was successfully updated."
    else
      render :action => "edit", :id => params[:id]
    end
  end
  
  def destroy
    @snippet = Snippet.find(params[:id])
    if @snippet.destroy
      redirect_to admin_snippets_path, :notice => "Snippet was deleted."
    else
      render :action => "index", :notice => "There was an error deleting the snippet."
    end
  end

  private
  def snippet_params
    params.require(:snippet).permit(:id, :name, :code, :category_id, {:attachment_ids => []}, :versions)
  end
  
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_filter :authorize!

  def show
    @snippet = Snippet.find(params[:id])
    respond_to do |format|
      format.html
      format.json {
        render json: @snippet
      }
    end
  end

  private
  def authorize!
    raise "You are not authorized!" unless can?(:manage, Snippet)
  end
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/admin/snippets/_snippet_form.html.slim
javascript:
  $.ctrl('S', function(){
    $('form.edit_snippet').submit();
  });

= raw version_start_end_js('snippet')

- if @snippet.errors.any?
  ul
    - @snippet.errors.full_messages.each do |msg|
      li = msg

= form_for @snippet, :url => @submit_path do |f|
  .row.form_example
    .col-md-3
      .form-group
        = f.label :name
        = f.text_field :name, :class => "form-control"
      
      .form-group
        = f.label :Category
        = collection_select(:snippet, :category_id, Category.order(:name), :id, :name, {}, {:class => "form-control input-sm"})

      hr
      .form-group
        = f.label :products
        = render :partial => 'admin/shared/multi_products_select', :locals => {:model => "snippet", :selected => @snippet.snippet_versions, :potential => @snippet.potential_products}

      .form-group#attachments_div
        hr
        = f.label :attachments
        .attachments_list
          - Attachment.all.each do |a|
            => check_box_tag "snippet[attachment_ids][]", a.id, @snippet.attachments.include?(a) 
            = label_tag "snippet[attachment_ids][#{a.id}]", a.file_file_name
            br

    .col-md-9
      #generic_code_container
        = f.label :generic_code
        span.pull-right
          => f.submit :class => "btn btn-primary btn-xs"
          = link_to "help", admin_help_path(:type => "examples"), :target => "_blank", :class => "btn btn-info btn-xs"
        .generic_code_box
          = f.text_area :code, :class => "edit_box_code"
          = render :partial => 'admin/shared/codemirror', :locals => {:container_id => 'snippet_code'}

app/views/admin/snippets/edit.html.slim
= render "snippet_form"

app/views/admin/snippets/index.html.slim
h2 
  => "Snippets"
  small
    = link_to new_admin_snippet_path do
      i.fa.fa-plus

- @categories.each do |c|
  h4 = c.name
  table.table
    tr
      th style="width: 40px" ID
      th Name
      th style="width: 30px"
    - c.snippets.each do |s|
      tr
        td = link_to s.id, edit_admin_snippet_path(s)
        td = link_to s.name, edit_admin_snippet_path(s)
        td = link_to "x", admin_snippet_path(s), :method => :delete, :confirm => "Are you sure?"

app/views/admin/snippets/new.html.slim
= render "snippet_form"