config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "snippets/show"

  get "/support/cookie", :controller => "support", :action => "cookie"

  get "/samples", :controller => "samples", :action => "index"
  get "/samples/:page" => "samples#show"
  post "/samples/:page" => "samples#show"
 
  namespace :admin do
    resources :examples, :products, :versions, :categories, :snippets, :attachments, :users
    get "/help/(:type)", :controller => "help", :action => "index", :as => "help"
    get "feedback/list", :controller => "feedback", :action => "list"
    get "feedback/list/:id", :controller => "feedback", :action => "view", :as => "example_feedback"
    delete "feedback/:id", :controller => "feedback", :action => "destroy", :as => "feedback_delete"
  end
  
  get "/js/:action(.:format)", :controller => "js"
  
  post "/feedback/(:id)", :controller => "feedbacks", :action => "create", :as => "feedbacks"

  get "/search/(:q)", :controller => "examples", :action => "search", :as => "examples_search"

  get "/examples(.:format)", :controller => "examples", :action => "index", :as => "examples_index"
  get "/legacy(.:format)", :controller => "examples", :action => "legacy", :as => "examples_legacy_index"

  get "/snippets/:id", controller: 'snippets', action: 'show'

  get "/:id(.:language)", :constraints => {:id => /[0-9]+/}, :controller => 'examples', :action => 'show_id', :as => 'example_id'
  get "/Toolkit_Professional(/:version(/:title(.:language)))", to: redirect { |path_params, req| "/Toolkit/#{path_params[:version]}/#{path_params[:title]}.#{path_params[:language]}" }
  get "/:product/:version/download.:language", :controller => "examples", :action => "download_all_examples", :as => "examples_download"
  get "/:product(/:version(/:title(.:language)))", :controller => "examples", :action => "show", :as => "examples"
  get "/:product/:version/:title.:language/documentation", :controller => "examples", :action => "documentation", :as => "example_documentation"
  get "/:product/:version/:title.:language/download", :controller => "examples", :action => "download", :as => "example_download"
  get "/:product/:version/:title.:language/download_all", :controller => "examples", :action => "download_all", :as => "example_download_all"
  get "/:product/:version/:title.:language/download_package", :controller => "examples", :action => "download_package", :as => "example_download_package"

  post "/contact_mailer", :controller => "contact", :action => "create"

  root :to => "examples#index"

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :new_token

  before_save :encrypt_token

  def encrypt_token
    self.token = ::BCrypt::Password.create(new_token).to_s if new_token.present?
  end  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource class: User

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_path(@user), notice: "User #{t(:create_success)}"
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "User #{t(:update_success)}"
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to admin_users_url, notice: "User #{t(:delete_success)}"
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :new_token, :admin, :qa, :support, :engineering)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.slim
= form_for @user, url: [:admin, @user] do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  = label_tag :email
  = f.text_field :email

  = label_tag :admin
  = f.check_box :admin

  = label_tag :qa
  = f.check_box :qa

  = label_tag :support
  = f.check_box :support

  = label_tag :engineering
  = f.check_box :engineering

  = label_tag :new_token
  = f.text_field :new_token

  - if @user.new_record?
    = label_tag :password
    = f.password_field :password

    = label_tag :password_confirmation
    = f.password_field :password_confirmation

  .actions = f.submit

app/views/admin/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', admin_user_path(@user)
'|
= link_to 'Back', admin_users_path

app/views/admin/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Email
      th Admin?
      th QA?
      th Support?
      th Engineering?
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.email
        td = user.admin?
        td = user.qa?
        td = user.support?
        td = user.engineering?
        td = link_to 'Show', admin_user_path(user)
        td = link_to 'Edit', edit_admin_user_path(user)
        td = link_to 'Destroy', admin_user_path(user), data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New User', new_admin_user_path

app/views/admin/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', admin_users_path

app/views/admin/users/show.html.slim
p#notice = notice

h1 = "User #{@user.email}"

= link_to 'Edit', edit_admin_user_path(@user)
'|
= link_to 'Back', admin_users_path